#version: '3.8'
#services:
#  postgres:
#    image: 'postgres'
#    volumes:
#      - ./volumes/postgresql-data:/var/lib/postgresql/data
##    restart: always
#    environment:
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=bootcamp
#    ports:
#      - '5432:5432'
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#  backend:
#    container_name: bootcamp
#    image: 'spring-docker-image'
##    restart: always
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5432/bootcamp
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=password
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    ports:
#      - '8080:8080'
version: '3.1'

services:
  backend:
    image: 'purap1e/spring-docker-image'
    container_name: bootcamp
    depends_on:
      - db
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080

  db:
    image: 'postgres'
    container_name: pg-server
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
